### ISSUE TITLE
Social Login plugin replaced default deeplink URL scheme

### ISSUE THREAD

**Issue by emilof** [OutSystems/cordova-outsystems-sociallogins#42]
We've been digging for a while why our app suddenly stopped responding to the default custom URL scheme. According to the OutSystems docs the URL scheme should be set to the value specified in the App Identifier field under Module / Distribute / Native Platform / iOS. 

When digging through the source code I found that this plugin actually sets that value in the `iOSCopyPreferences.js` hook. It fetches a JSON config (endpoint specified in the app's Extensibility Configurations) from the SocialLoginConfigurator and uses the value found under `app_deeplink.url_scheme`.

If I understand the code correct it looks like the hook replaces the existing array for the **DeepLinkScheme** (`CFBundleURLName`), with a new array instead of pushing the value onto the existing one.  

Do you have any suggestions how to solve this issue without updating the source code of this plugin?

**Comment by OS-ricardomoreirasilva** [comment]
Hey @emilof.

Apologies for the late reply.
The latest 2.0.2 release already has this issue fixed. Please try it and, if it works, we can close the issue.

Best regards.
